### ISSUE TITLE
Experiment with RoBERTa/ALBERT

### ISSUE THREAD

**Issue by JohnGiorgi** [JohnGiorgi/DeCLUTR#13]
# Overview

Both RoBERTa and ALBERT outperform BERT on almost every downstream task. ALBERT has the additional benefit of having many times fewer parameters. The authors also demonstrated that it scales better (i.e. they don't observe the same degradation in model performance when they increase the model size and training set size as they do with BERT).

For these reasons, ALBERT is likely our best choice for the encoder. To confirm this, train the model using BERT, RoBERTa and ALBERT and compare the quality of the produced embeddings.

## TODO

- [x] Train the model with BERT, inspect the embeddings in tensorboard (qualitative) and  assess  their performance on the document retrival task (quantitative)
- [x] Repeat for RoBERTa
- [x] Repeat for ALBERT
- [x] Make the winner the default encoder
